---
version: '3.8'
services:
  user-service:
    build: ./user-service/api/
    container_name: user-service
    depends_on: [postgres]
    environment:
      PORT: 8081
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8081:8081]
    networks: [marketplace-network]
  product-service:
    build: ./product-service/api/
    container_name: product-service
    depends_on: [postgres]
    environment:
      PORT: 8082
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8082:8082]
    networks: [marketplace-network]
networks:
  marketplace-network:
    driver: bridge
volumes:
  pgdata:
