---
version: '3.8'
services:
  user-service:
    build: ./user-service/api
    container_name: users-service
    command: [./main]
    depends_on: [postgres]
    environment:
      PORT: 8080
      SERVER_HOST: localhost
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8080:8080]
    networks: [kong-network]
  # product-service:
  #   build:
  #     context: ./product-service
  #   container_name: product-service
  #   ports:
  #     - 8002:8000  # Измените на нужный порт
  #   networks: [kong-network]
  kong:
    image: kong:latest
    ports:
      - 8000:8000  # Порт для API
      - 8001:8001  # Порт для админки
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres  # Имя сервиса PostgreSQL
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: barghest  # Убедитесь, что этот пароль соответствует паролю PostgreSQL
      KONG_PG_DATABASE: kong  # Имя базы данных Kong
    networks: [kong-network]
    depends_on: [postgres]
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
    networks: [kong-network]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:80]
    networks: [kong-network]
volumes:
  pgdata:
networks:
  kong-network:
    driver: bridge
