---
version: '3.8'
services:
  user-service:
    build: ./user-service/api/
    container_name: user-service
    depends_on: [postgres]
    environment:
      PORT: 8081
      SERVER_HOST: localhost
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8081:8081]
    networks: [marketplace-network]
  product-service:
    build: ./product-service/api/
    container_name: product-service
    depends_on: [postgres]
    environment:
      PORT: 8082
      SERVER_HOST: localhost
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8082:8082]
    networks: [marketplace-network]
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: kong
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
    networks: [marketplace-network]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:5050]
    networks: [marketplace-network]
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    networks: [marketplace-network]

networks:
  marketplace-network:
    driver: bridge
volumes:
  pgdata:
