---
version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: your_password
    volumes: [postgres_data:/var/lib/postgresql/data]
    networks: [backend]
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: your_password
      KONG_PG_DATABASE: kong
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong-config.yaml
    volumes: [./kong-config.yaml:/etc/kong/kong-config.yaml]
    ports:
      - 8000:8000  # Public API
      - 8001:8001  # Admin API
    depends_on: [postgres]
    networks: [backend]
  user-service:
    build:
      context: ./user-service
    ports: [8080:8080]
    networks: [backend]
  product-service:
    build:
      context: ./product-service
    ports: [8081:8080]
    networks: [backend]
volumes:
  postgres_data:
networks:
  backend:
