---
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
    networks: [marketplace-network]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:80]
    networks: [marketplace-network]
  kong:
    build: ./api-gateway/
    restart: always
    container_name: kong
    ports:
      - 8000:8000  # Port for accessing the API
      - 8001:8001  # Port for admin API
    environment:
      KONG_LOG_LEVEL: debug
      KONG_DATABASE: off
      KONG_PG_HOST: postgres
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: barghest
    networks: [marketplace-network]
    depends_on: [postgres]
    volumes: [./api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml]
  user-service:
    build: ./user-service/api/
    container_name: user-service
    depends_on: [postgres]
    environment:
      PORT: 8081
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8081:8081]
    networks: [marketplace-network]
  product-service:
    build: ./product-service/api/
    container_name: product-service
    depends_on: [postgres]
    environment:
      PORT: 8082
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8082:8082]
    networks: [marketplace-network]
networks:
  marketplace-network:
    driver: bridge
volumes:
  pgdata:
