---
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      #db
      POSTGRES_DB: kong
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
    networks: [marketplace-network]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:80]
    networks: [marketplace-network]
  kong:
    #image
    image: kong/kong-gateway:2.7.2.0-alpine
    restart: always
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: barghest
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    depends_on: [postgres]
    #путь
    volumes:
      - ./api-gateway/kong.yml:/usr/local/kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks: [marketplace-network]
    # command
    command: >
      sh -c "kong migrations bootstrap && kong start"
  user-service:
    build: ./user-service/api/
    container_name: user-service
    depends_on: [postgres]
    environment:
      PORT: 8081
      SERVER_HOST: user-service
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8081:8081]
    networks: [marketplace-network]
  product-service:
    build: ./product-service/api/
    container_name: product-service
    depends_on: [postgres]
    environment:
      PORT: 8082
      SERVER_HOST: product-service 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8082:8082]
    networks: [marketplace-network]
networks:
  marketplace-network:
    driver: bridge
volumes:
  pgdata:
