---
version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [5432:5432]
    volumes: [pgdata:/var/lib/postgresql/data]
    networks: [products-network]
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:80]
    networks: [products-network]
  product-service:
    build: .
    container_name: product-service
    depends_on: [postgres]
    environment:
      PORT: 8080
      SERVER_HOST: localhost
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8080:8080]
    networks: [products-network]
networks:
  products-network:
    driver: bridge
volumes:
  pgdata:
