version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
      DB_PORT: 5432
      DB_HOST: localhost
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:

