version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:barghest@postgres:5432/users?sslmode=disable
    command: ["./main"]

volumes:
  pgdata:
