version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports:
      - "5050:80"


  # app:
    # build: .
    # container_name: app
    # depends_on:
    #   - db
    # command: ["./main"]

volumes:
  pgdata:
