version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - user

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports:
      - "5050:80"
    networks:
      - user



  app:
    build: .
    container_name: app
    depends_on:
      - db
    command: ["./main"]
    environment:
      PORT: 8080
      SERVER_HOST: localhost
      DB_HOST: db
      DB_PORT: 5432

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    networks:
      - user

networks:
  user:
    driver: bridge


volumes:
  db-data:
