---
version: '3.8'
services:
  users-api:
    build:
      context: ./api
      dockerfile: ./api/Dockerfile
    container_name: users-api
    environment:
      PORT: 8080
      SERVER_HOST: localhost
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8080:8080]
    networks: [kong-network]
